"""
Lightweight docs generator stub for tests.
"""

from typing import Dict, Any


class DocsGenerator:
	async def generate(self, files: Dict[str, str], schema: Dict[str, Any], context: Dict[str, Any]) -> Dict[str, str]:
		return {
			"README.md": (
				"# Project\n"
				"This project was generated by codebegen.\n"
			)
		}


docs_generator = DocsGenerator()
